### ISSUE TITLE
"Possible Unhandled Promise Rejection" when trying to test on device

### ISSUE THREAD

**Issue by aaronfg** [BulletTrainHQ/react-native-performance-monitor#10]
I added the 3rd param to the export to test on a real device, as stated in the docs:

```
export default withPerformanceMonitor(Meeting, 'Meeting', '192.168.1.142');
```

But I still get warnings (hundreds) when I get to that screen as the server can't connect to the device it seems:

```
Possible Unhandled Promise Rejection (id:379):
TypeError: Network request failed
```

Not sure what is going wrong here as the ip of my device is correct (I can ping it form the terminal fine)

**Comment by kyle-ssg** [comment]
Did you try this in debug mode with the network tab to see what was sent @aaronfg ?

**Comment by aaronfg** [comment]
> Did you try this in debug mode with the network tab 

Not yet, sorry. Got sidetracked with other work. 

I'll test and report back.

**Comment by PierreCapo** [comment]
Hello,
The same happens to me. @kyle-ssg we can do a live debug session if you want to debug that.
Thanks a lot for your lib, it is really great 👍

**Comment by kyle-ssg** [comment]
If you launch something like react-native-debugger you'll be able to get a cURL request, I'd imagine it'll be some typo in the url.

**Comment by kyle-ssg** [comment]
Closing, please re-open if you have issues - thanks.

**Comment by alittletf** [comment]
Hey @aaronfg / @PierreCapo were you able to get this working? I have the same issue. 

@kyle-ssg - any idea what might the issue? I've tried running on device and in the simulator and getting the same error. I am struggling to figure out what I need to change since it took very little code to get setup. 

My error: 
![image](https://user-images.githubusercontent.com/17679691/90174902-874db280-dd5b-11ea-9dba-f43814d070d9.png)

**Comment by hamzawaleed01** [comment]
Same issue, `it's calling 127.0.0.1:8125/value` endpoint
